# Inspired by:
# https://github.com/omf2/core-plugin-pack/blob/main/themes/omz/robbyrussell.toml

format = """
$character\
$directory\
${custom.git_prefix}\
$git_branch\
$git_commit\
${custom.git_suffix}\
${custom.git_status_dirty}
"""

right_format = """
$python\
$golang\
"""

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[directory]
style = "bold cyan"

[git_branch]
format = "[$branch]($style)"
style = "bold red"

[git_commit]
format = "[ $hash$tag]($style)"
style = "bold red"

[custom.git_prefix]
when = 'git rev-parse --is-inside-work-tree'
symbol = "git:\\("
format = "[$symbol]($style)"
style = "bold blue"

[custom.git_suffix]
when = 'git rev-parse --is-inside-work-tree'
symbol = "\\) "
format = "[$symbol]($style)"
style = "bold blue"

[custom.git_status_dirty]
when = 'test -n "$(git status --porcelain)"'
symbol = "* "
format = "[$symbol]($style)"
style = "bold yellow"

[python]
format = "[$virtualenv]($style)"
style = "bright-black"

[golang]
format = "[$version]($style)"
style = "bright-black"
