# Themes source:
# https://github.com/alacritty/alacritty-theme

[general]
import = ["~/.config/alacritty/themes/themes/monokai.toml"]

[font]
size = 16

[font.normal]
# family = "Hack Nerd Font"
family = "FiraCode Nerd Font"

[window]
opacity = 0.5
blur = true

[window.padding]
x = 8
y = 8
